=== yaoh4/greensheets_classic/Implementation/GsApp/trunk/database/src/gov/nih/nci/cbiit/scimgmt/gsdb/domain/oldgsfb/GsForm.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
	Purpose: XML Schema Definition file for the new Form XML format.  
	Author: Krishna M. Kanchinadam
	Company: Number Six Software
	Date: 09/03/2003
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="unqualified" attributeFormDefault="unqualified">
	<!-- Definition of Basic Data Types - Start -->
	<xs:simpleType name="dataType_string_1">
		<xs:restriction base="xs:string">
			<xs:maxLength value="1"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="dataType_String_10">
		<xs:restriction base="xs:string">
			<xs:maxLength value="10"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="dataType_String_20">
		<xs:restriction base="xs:string">
			<xs:maxLength value="20"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="dataType_String_50">
		<xs:restriction base="xs:string">
			<xs:maxLength value="50"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="dataType_String_100">
		<xs:restriction base="xs:string">
			<xs:maxLength value="100"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="dataType_String_200">
		<xs:restriction base="xs:string">
			<xs:maxLength value="200"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="dataType_String_250">
		<xs:restriction base="xs:string">
			<xs:maxLength value="250"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="dataType_String_65534">
		<xs:restriction base="xs:string">
			<xs:maxLength value="65534"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="dataType_Decimal">
		<xs:restriction base="xs:decimal"/>
	</xs:simpleType>
	<xs:simpleType name="dataType_Double">
		<xs:restriction base="xs:double"/>
	</xs:simpleType>
	<xs:simpleType name="dataType_PositiveInteger">
		<xs:restriction base="xs:positiveInteger"/>
	</xs:simpleType>
	<xs:simpleType name="dataType_Date">
		<xs:restriction base="xs:date"/>
	</xs:simpleType>
	<xs:simpleType name="dataType_Boolean">
		<xs:restriction base="xs:boolean"/>
	</xs:simpleType>
	<!-- Definition of Basic Data Types - End -->
	<!-- Definition of Simple Data Types - Start -->
	<xs:simpleType name="GreensheetFormId">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>
	<xs:simpleType name="QuestionDefId">
		<xs:restriction base="xs:string">
			<xs:pattern value="([A-Z])+[_][1-9]([0-9])*"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ResponseDefId">
		<xs:restriction base="xs:string">
			<xs:pattern value="([A-Z])+[_][1-9]([0-9])*[_][R][D][_](TX|NU|ST|DT|RB|DD|CB|FL|CM)[_][1-9]([0-9])*"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="SelectionDefId">
		<xs:restriction base="xs:string">
			<xs:pattern value="([S][E][L][_][X_]*[1-9]([0-9])*)"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="GrantType">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>
	<xs:simpleType name="GrantMech">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>
	<xs:simpleType name="QuestionText">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>
	<xs:simpleType name="QuestionInstructions">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>
	<xs:simpleType name="SelectionValue">
		<xs:restriction base="xs:string"/>
	</xs:simpleType>
	<xs:simpleType name="ResponseTypes">
		<xs:restriction base="xs:string">
			<xs:enumeration value="COMMENT"/>
			<xs:enumeration value="CHECK_BOX"/>
			<xs:enumeration value="DATE"/>
			<xs:enumeration value="DROP_DOWN"/>
			<xs:enumeration value="FILE"/>
			<xs:enumeration value="NUMBER"/>
			<xs:enumeration value="RADIO"/>
			<xs:enumeration value="STRING"/>
			<xs:enumeration value="TEXT"/>
		</xs:restriction>
	</xs:simpleType>
	<!-- Definition of Simple Data Types - End -->
	<!-- Definition of Simple Elements - Start -->
	<!-- These simple elements are being declared here with the appropriate type. The elements would be used in constructing the XML document. Defining elements in this manner 
		promotes re-use of the same element from multiple locations in the XML document.  -->
	<xs:complexType name="SelectionDefElement">
		<xs:sequence>
			<xs:element name="Value" type="SelectionValue"/>
			<xs:element name="QuestionDef" type="QuestionDefElement" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="SelectionDefId" use="required"/>
	</xs:complexType>
	<xs:complexType name="ResponseDefElement">
		<xs:sequence>
			<xs:element name="SelectionDef" type="SelectionDefElement" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="ResponseDefId" use="required"/>
		<xs:attribute name="type" type="ResponseTypes" use="required"/>
	</xs:complexType>
	<xs:complexType name="ResponseDefsListElement">
		<xs:sequence>
			<xs:element name="ResponseDef" type="ResponseDefElement" maxOccurs="3"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="GrantTypeMechsElement">
		<xs:sequence>
			<xs:element name="TypeMech" type="TypeMechElement" maxOccurs="unbounded"></xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="QuestionDefElement">
		<xs:sequence>
			<xs:element name="GrantTypeMechs" type="GrantTypeMechsElement">
				<xs:key name="keyTypeMech">
					<xs:selector xpath="./TypeMech"></xs:selector>
					<xs:field xpath="@type"></xs:field>
					<xs:field xpath="@mech"></xs:field>				
				</xs:key>
			</xs:element>
			<xs:element name="QText" type="QuestionText"/>
			<xs:element name="QInstructions" type="QuestionInstructions"/>
			<xs:element name="ResponseDefsList" type="ResponseDefsListElement"/>
		</xs:sequence>
		<xs:attribute name="id" type="QuestionDefId" use="required"/>
	</xs:complexType>
	<xs:complexType name="TypeMechElement">
		<xs:attribute name="type" type="GrantType" use="required"/>
		<xs:attribute name="mech" type="GrantMech" use="required"/>
	</xs:complexType>
	<xs:complexType name="GreensheetQuestionsElement">
		<xs:sequence>
			<xs:element name="QuestionDef" type="QuestionDefElement" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="GreensheetFormId"/>
	</xs:complexType>
	<xs:complexType name="GreensheetFormElement">
		<xs:sequence>
			<xs:element name="GreensheetQuestions" type="GreensheetQuestionsElement">
				<xs:key name="keyQuestionDefId">
					<xs:selector xpath=".//QuestionDef"/>
					<xs:field xpath="@id"/>
				</xs:key>
				<xs:key name="keyResponseDefId">
					<xs:selector xpath=".//ResponseDef"/>
					<xs:field xpath="@id"/>
				</xs:key>
				<xs:key name="keySelectionDefId">
					<xs:selector xpath=".//SelectionDef"/>
					<xs:field xpath="@id"/>
				</xs:key>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="GreensheetForm" type="GreensheetFormElement">
	</xs:element>
</xs:schema>

=== yaoh4/greensheets_classic/Implementation/GsQuestions/trunk/xmlPreparation/xml/DNC_Questions before nesting.xml
<?xml version="1.0" encoding="UTF-8"?>
<GreensheetQuestions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="..\schema\GsForm.xsd">
  <QuestionDef id="DMNCQ_110">
    <GrantTypeMechs>
      <TypeMech type="5" mech="C06"/>
      <TypeMech type="8" mech="C06"/>
      <TypeMech type="5" mech="F30"/>
      <TypeMech type="8" mech="F30"/>
      <TypeMech type="5" mech="F31"/>
      <TypeMech type="8" mech="F31"/>
      <TypeMech type="5" mech="F32"/>
      <TypeMech type="8" mech="F32"/>
      <TypeMech type="5" mech="F33"/>
      <TypeMech type="8" mech="F33"/>
      <TypeMech type="5" mech="K01"/>
      <TypeMech type="8" mech="K01"/>
      <TypeMech type="5" mech="K04"/>
      <TypeMech type="8" mech="K04"/>
      <TypeMech type="5" mech="K05"/>
      <TypeMech type="8" mech="K05"/>
      <TypeMech type="5" mech="K07"/>
      <TypeMech type="8" mech="K07"/>
      <TypeMech type="5" mech="K08"/>
      <TypeMech type="8" mech="K08"/>
      <TypeMech type="5" mech="K11"/>
      <TypeMech type="8" mech="K11"/>
      <TypeMech type="5" mech="K12"/>
      <TypeMech type="8" mech="K12"/>
      <TypeMech type="5" mech="K14"/>
      <TypeMech type="8" mech="K14"/>
      <TypeMech type="5" mech="K22"/>
      <TypeMech type="8" mech="K22"/>
      <TypeMech type="5" mech="K23"/>
      <TypeMech type="8" mech="K23"/>
      <TypeMech type="5" mech="K24"/>
      <TypeMech type="8" mech="K24"/>
      <TypeMech type="5" mech="K25"/>
      <TypeMech type="8" mech="K25"/>
      <TypeMech type="5" mech="K99"/>
      <TypeMech type="8" mech="K99"/>
      <TypeMech type="5" mech="KL1"/>
      <TypeMech type="8" mech="KL1"/>
      <TypeMech type="5" mech="KL2"/>
      <TypeMech type="8" mech="KL2"/>
      <TypeMech type="5" mech="P01"/>
      <TypeMech type="8" mech="P01"/>
      <TypeMech type="5" mech="P20"/>
      <TypeMech type="8" mech="P20"/>
      <TypeMech type="5" mech="P30"/>
      <TypeMech type="8" mech="P30"/>
      <TypeMech type="5" mech="P50"/>
      <TypeMech type="8" mech="P50"/>
      <TypeMech type="5" mech="PL1"/>
      <TypeMech type="8" mech="PL1"/>
      <TypeMech type="5" mech="R00"/>
      <TypeMech type="8" mech="R00"/>
      <TypeMech type="5" mech="R01"/>
      <TypeMech type="8" mech="R01"/>
      <TypeMech type="5" mech="R03"/>
      <TypeMech type="8" mech="R03"/>
      <TypeMech type="5" mech="R13"/>
      <TypeMech type="8" mech="R13"/>
      <TypeMech type="5" mech="R15"/>
      <TypeMech type="8" mech="R15"/>
      <TypeMech type="5" mech="R18"/>
      <TypeMech type="8" mech="R18"/>
      <TypeMech type="5" mech="R21"/>
      <TypeMech type="8" mech="R21"/>
      <TypeMech type="5" mech="R24"/>
      <TypeMech type="8" mech="R24"/>
      <TypeMech type="5" mech="R25"/>
      <TypeMech type="8" mech="R25"/>
      <TypeMech type="5" mech="R29"/>
      <TypeMech type="8" mech="R29"/>
      <TypeMech type="5" mech="R33"/>
      <TypeMech type="8" mech="R33"/>
      <TypeMech type="5" mech="R35"/>
      <TypeMech type="8" mech="R35"/>
      <TypeMech type="5" mech="R37"/>
      <TypeMech type="8" mech="R37"/>
      <TypeMech type="5" mech="R41"/>
      <TypeMech type="8" mech="R41"/>
      <TypeMech type="5" mech="R42"/>
      <TypeMech type="8" mech="R42"/>
      <TypeMech type="5" mech="R43"/>
      <TypeMech type="8" mech="R43"/>
      <TypeMech type="5" mech="R44"/>
      <TypeMech type="8" mech="R44"/>
      <TypeMech type="5" mech="R55"/>
      <TypeMech type="8" mech="R55"/>
      <TypeMech type="5" mech="R56"/>
      <TypeMech type="8" mech="R56"/>
      <TypeMech type="5" mech="RL1"/>
      <TypeMech type="8" mech="RL1"/>
      <TypeMech type="5" mech="RL2"/>
      <TypeMech type="8" mech="RL2"/>
      <TypeMech type="5" mech="RL5"/>
      <TypeMech type="8" mech="RL5"/>
      <TypeMech type="5" mech="RL9"/>
      <TypeMech type="8" mech="RL9"/>
      <TypeMech type="5" mech="S15"/>
      <TypeMech type="8" mech="S15"/>
      <TypeMech type="5" mech="SC1"/>
      <TypeMech type="8" mech="SC1"/>
      <TypeMech type="5" mech="SC2"/>
      <TypeMech type="8" mech="SC2"/>
      <TypeMech type="5" mech="T15"/>
      <TypeMech type="8" mech="T15"/>
      <TypeMech type="5" mech="T32"/>
      <TypeMech type="8" mech="T32"/>
      <TypeMech type="5" mech="TL1"/>
      <TypeMech type="8" mech="TL1"/>
      <TypeMech type="5" mech="TU2"/>
      <TypeMech type="8" mech="TU2"/>
      <TypeMech type="5" mech="U01"/>
      <TypeMech type="8" mech="U01"/>
      <TypeMech type="5" mech="U09"/>
      <TypeMech type="8" mech="U09"/>
      <TypeMech type="5" mech="U10"/>
      <TypeMech type="8" mech="U10"/>
      <TypeMech type="5" mech="U13"/>
      <TypeMech type="8" mech="U13"/>
      <TypeMech type="5" mech="U19"/>
      <TypeMech type="8" mech="U19"/>
      <TypeMech type="5" mech="U24"/>
      <TypeMech type="8" mech="U24"/>
      <TypeMech type="5" mech="U43"/>
      <TypeMech type="8" mech="U43"/>
      <TypeMech type="5" mech="U44"/>
      <TypeMech type="8" mech="U44"/>
      <TypeMech type="5" mech="U54"/>
      <TypeMech type="8" mech="U54"/>
      <TypeMech type="5" mech="U56"/>
      <TypeMech type="8" mech="U56"/>
      <TypeMech type="5" mech="UL1"/>
      <TypeMech type="8" mech="UL1"/>
    </GrantTypeMechs>
    <QText>Was this application received electronically?</QText>
    <QInstructions/>
    <ResponseDefsList>
      <ResponseDef id="DMNCQ_110_RD_CM_1" type="COMMENT"/>
      <ResponseDef id="DMNCQ_110_RD_FL_1" type="FILE"/>
      <ResponseDef id="DMNCQ_110_RD_RB_1" type="RADIO">
        <SelectionDef id="SEL_8001">
          <Value>Yes</Value>
        </SelectionDef>
        <SelectionDef id="SEL_8002">
          <Value>No</Value>
        </SelectionDef>
      </ResponseDef>
    </ResponseDefsList>
  </QuestionDef>
  <QuestionDef id="DMNCQ_120">
    <GrantTypeMechs>
      <TypeMech type="5" mech="C06"/>
      <TypeMech type="8" mech="C06"/>
      <TypeMech type="5" mech="F30"/>
      <TypeMech type="8" mech="F30"/>
      <TypeMech type="5" mech="F31"/>
      <TypeMech type="8" mech="F31"/>
      <TypeMech type="5" mech="F32"/>
      <TypeMech type="8" mech="F32"/>
      <TypeMech type="5" mech="F33"/>
      <TypeMech type="8" mech="F33"/>
      <TypeMech type="5" mech="K01"/>
      <TypeMech type="8" mech="K01"/>
      <TypeMech type="5" mech="K04"/>
      <TypeMech type="8" mech="K04"/>
      <TypeMech type="5" mech="K05"/>
      <TypeMech type="8" mech="K05"/>
      <TypeMech type="5" mech="K07"/>
      <TypeMech type="8" mech="K07"/>
      <TypeMech type="5" mech="K08"/>
      <TypeMech type="8" mech="K08"/>
      <TypeMech type="5" mech="K11"/>
      <TypeMech type="8" mech="K11"/>
      <TypeMech type="5" mech="K12"/>
      <TypeMech type="8" mech="K12"/>
      <TypeMech type="5" mech="K14"/>
      <TypeMech type="8" mech="K14"/>
      <TypeMech type="5" mech="K22"/>
      <TypeMech type="8" mech="K22"/>
      <TypeMech type="5" mech="K23"/>
      <TypeMech type="8" mech="K23"/>
      <TypeMech type="5" mech="K24"/>
      <TypeMech type="8" mech="K24"/>
      <TypeMech type="5" mech="K25"/>
      <TypeMech type="8" mech="K25"/>
      <TypeMech type="5" mech="K99"/>
      <TypeMech type="8" mech="K99"/>
      <TypeMech type="5" mech="KL1"/>
      <TypeMech type="8" mech="KL1"/>
      <TypeMech type="5" mech="KL2"/>
      <TypeMech type="8" mech="KL2"/>
      <TypeMech type="5" mech="P01"/>
      <TypeMech type="8" mech="P01"/>
      <TypeMech type="5" mech="P20"/>
      <TypeMech type="8" mech="P20"/>
      <TypeMech type="5" mech="P30"/>
      <TypeMech type="8" mech="P30"/>
      <TypeMech type="5" mech="P50"/>
      <TypeMech type="8" mech="P50"/>
      <TypeMech type="5" mech="PL1"/>
      <TypeMech type="8" mech="PL1"/>
      <TypeMech type="5" mech="R00"/>
      <TypeMech type="8" mech="R00"/>
      <TypeMech type="5" mech="R01"/>
      <TypeMech type="8" mech="R01"/>
      <TypeMech type="5" mech="R03"/>
      <TypeMech type="8" mech="R03"/>
      <TypeMech type="5" mech="R13"/>
      <TypeMech type="8" mech="R13"/>
      <TypeMech type="5" mech="R15"/>
      <TypeMech type="8" mech="R15"/>
      <TypeMech type="5" mech="R18"/>
      <TypeMech type="8" mech="R18"/>
      <TypeMech type="5" mech="R21"/>
      <TypeMech type="8" mech="R21"/>
      <TypeMech type="5" mech="R24"/>
      <TypeMech type="8" mech="R24"/>
      <TypeMech type="5" mech="R25"/>
      <TypeMech type="8" mech="R25"/>
      <TypeMech type="5" mech="R29"/>
      <TypeMech type="8" mech="R29"/>
      <TypeMech type="5" mech="R33"/>
      <TypeMech type="8" mech="R33"/>
      <TypeMech type="5" mech="R35"/>
      <TypeMech type="8" mech="R35"/>
      <TypeMech type="5" mech="R37"/>
      <TypeMech type="8" mech="R37"/>
      <TypeMech type="5" mech="R41"/>
      <TypeMech type="8" mech="R41"/>
      <TypeMech type="5" mech="R42"/>
      <TypeMech type="8" mech="R42"/>
      <TypeMech type="5" mech="R43"/>
      <TypeMech type="8" mech="R43"/>
      <TypeMech type="5" mech="R44"/>
      <TypeMech type="8" mech="R44"/>
      <TypeMech type="5" mech="R55"/>
      <TypeMech type="8" mech="R55"/>
      <TypeMech type="5" mech="R56"/>
      <TypeMech type="8" mech="R56"/>
      <TypeMech type="5" mech="RL1"/>
      <TypeMech type="8" mech="RL1"/>
      <TypeMech type="5" mech="RL2"/>
      <TypeMech type="8" mech="RL2"/>
      <TypeMech type="5" mech="RL5"/>
      <TypeMech type="8" mech="RL5"/>
      <TypeMech type="5" mech="RL9"/>
      <TypeMech type="8" mech="RL9"/>
      <TypeMech type="5" mech="S15"/>
      <TypeMech type="8" mech="S15"/>
      <TypeMech type="5" mech="SC1"/>
      <TypeMech type="8" mech="SC1"/>
      <TypeMech type="5" mech="SC2"/>
      <TypeMech type="8" mech="SC2"/>
